# Generated by Django 6.0.3 on 2026-03-20 10:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metric',
            old_name='load',
            new_name='disk_usage',
        ),
        migrations.RemoveField(
            model_name='server',
            name='owner',
        ),
        migrations.AddField(
            model_name='server',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='server',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
