# Generated by Django 6.0.3 on 2026-03-20 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_usertoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
